version: '3.2'

services:
  spacy-vector-api:
    build: ./spacy-vector-api
    volumes: 
      - './spacy-vector-api:/usr/src/app'
    ports:
      - 5001:80

  express-backend:
    build: ./express-backend
    volumes: 
      - './express-backend:/usr/src/app'
    ports:
      - 5000:3000
    depends_on:
      - spacy-vector-api