version: '3.3'

services:
  spacy-vector-api:
    build: ./spacy-vector-api
    volumes: 
      - type: bind
        source: ./spacy-vector-api
        target: /usr/src/spacyapi
    ports:
      - 5001:80

  express-backend:
    build: ./express-backend
    volumes: 
      - type: bind
        source: ./express-backend
        target: /usr/src/express-backend
    ports:
      - 5000:3000
    depends_on:
      - spacy-vector-api

  angular-frontend:
    build: ./angular-frontend
    volumes: 
      - type: bind
        source: ./angular-frontend
        target: /usr/src/angular-frontend
    ports:
      - 4200:4200
    depends_on:
      - spacy-vector-api
      - express-backend